// 70ecafa17e3ab7b25e2edd09b42a0f108cfb1e74
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "Gibbon's 64bit Git Build"
#define GIT_HASH "70ecafa17e3ab7b25e2edd09b42a0f108cfb1e74"
#define GIT_TIME "2021-08-28 09:25:43 +0200"
