// 0
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION " - Gibbon's Unofficial Git Build"
#define GIT_HASH "0"
#define GIT_TIME ""
